stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building project..."

deploy:
  stage: deploy
  before_script:
    - apt-get update -y
    - apt-get install -y git
  script:
    - git config --global user.email "dylanwood97@gmail.com"
    - git config --global user.name "dwood-97"
    - git checkout $CI_COMMIT_BRANCH
    - git merge origin/master
    - git push --set-upstream origin $CI_COMMIT_BRANCH
  only:
    - dev