# POSSIBLE GITLAB SETUP

stages:
  - build
  - post_build
  - deploy
  - test

image: arm64v8/ubuntu:focal-20230126

before_script:
  - ln -sf /usr/share/zoneinfo/UTC /etc/localtime
  - apt-get update && apt-get upgrade -y
  - apt-get install apt-utils -y
  - apt-get install ansible -y
  - apt-get install aptitude -y
  - apt-get install apt-transport-https -y
  - apt-get install build-essential -y
  - apt-get install ca-certificates -y
  - apt-get install curl -y
  - apt-get install git -y
  - apt-get install iptables -y
  - apt-get install libssl-dev -y
  - apt-get install python3-setuptools -y
  - apt-get install python3-dev -y
  - apt-get install python3-pip -y
  - apt-get install software-properties-common -y
  - apt-get install sudo -y
  - git clone https://gitlab.com/dwood-97/dora_containernet.git

Containernet Build:
  stage: build
  script:
    - echo "Installing Containernet...\n"
    - git clone https://github.com/containernet/containernet.git
    - ansible-playbook -i "localhost," -c local containernet/ansible/install.yml
  tags:
    - containernet

Dora Build:
  stage: build 
  script:
    - echo "Building Dora binary...\n"
    - git clone https://github.com/bluecatengineering/dora
    - mkdir dora/ansible
    - mv $HOME/dora_install.yml $HOME/dora/ansible/dora_install.yml
    - ansible-playbook -i "localhost," -c local dora/ansible/dora_install.yml
  tags:
    - dora

Build Docker images:
  stage: post_build
  script:
    - echo "Building Docker images...\n"
    - containernet/examples/example-containers/build.sh

# Containernet runner will hold containernet CLI open
Start Containernet:
  stage: deploy
  script:
    - echo "Starting Containernet...\n"
    - mkdir containernet/config
    - mv test.py containernet/config/test.py
    - python3 containernet/config/test.py
  dependencies:
    - "Build Docker images"
  tags:
    - containernet

Start Dora:
  stage: deploy
  script:
    - echo "Starting Dora on container "mn.d1""
    - docker exec mn.d1 mkdir /var/lib/dora
    - docker exec mn.d1 mv dora/config/test.yml /var/lib/dora
    - docker exec mn.d1 DORA_LOG="debug" dora/target/debug/dora -c dora/config/test.yaml -d dora/h1.db
  tags:
    - dora
