# POSSIBLE GITLAB SETUP

stages:
  - build
  - post_build
  - deploy
  - test

image: arm64v8/ubuntu:focal-20230126

before_script:
  - $BEFORE_SCRIPT

Containernet Build:
  stage: build
  script:
    - echo "Installing Containernet...\n"
    - git clone https://github.com/containernet/containernet.git
    - ansible-playbook -i "localhost," -c local containernet/ansible/install.yml
  tags:
    - containernet

Dora Build:
  stage: build 
  script:
    - echo "Building Dora binary...\n"
    - git clone https://gitlab.com/dwood-97/dora_containernet.git
    - bash /dora_containernet/dora_boot.bash
    - PATH="$HOME"/dora/target/debug:$PATH
  tags:
    - dora

Build Docker images:
  stage: post_build
  script:
    - echo "Building Docker images...\n"
    - containernet/examples/example-containers/build.sh

# Containernet runner will hold containernet CLI open
Start Containernet:
  stage: deploy
  script:
    - echo "Starting Containernet...\n"
    - mkdir containernet/config
    - mv test.py containernet/config/test.py
    - python3 containernet/config/test.py
  dependencies:
    - "Build Docker images"
  tags:
    - containernet

Start Dora:
  stage: deploy
  script:
    - echo "Starting Dora on container "mn.d1""
    - docker exec mn.d1 mkdir /var/lib/dora
    - docker exec mn.d1 mv dora/config/test.yml /var/lib/dora
    - docker exec mn.d1 DORA_LOG="debug" dora/target/debug/dora -c dora/config/test.yaml -d dora/h1.db
  tags:
    - dora
